### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by phuongth-0535** [phuongth-0535/figma-plugin-demo#35]
```tsx
// HomePage.tsx
import React from 'react';
import '~/components/Button';

const HomePage: React.FC = () => {
  return (
    <section className="homepage">
      <svg
        className="homepage-arrow"
        width="112.801px"
        height="2px"
        viewBox="0 0 112.801 2"
        style={{ transform: 'rotate(-37.073deg)' }}
        xmlns="http://www.w3.org/2000/svg"
      >
        <line x1="0" y1="1" x2="112.801" y2="1" stroke="#000" strokeWidth="2" />
      </svg>

      <Button text="Sign up" />

      <div className="header">
        <Button text="Login" />
        <div className="company-name">Company</div>
      </div>
    </section>
  );
};

export default HomePage;
```

```css
/* HomePage.css */
.homepage-arrow {
  stroke-width: 2px;
  stroke: #000;
}

.header {
  display: flex;
  width: 317px;
  height: 45px;
  padding: 8px 9px 9px 0px;
  align-items: center;
  gap: 143px;
  flex-shrink: 0;
  background: #8250DF;
}

.company-name {
  display: flex;
  width: 82px;
  height: 24px;
  flex-direction: column;
  justify-content: center;
  flex-shrink: 0;
  color: #FFF;
  text-align: center;
  font-family: Inter, sans-serif;
  font-size: 12px;
  font-weight: 400;
}
```

[Open in Figma](https://www.figma.com/file/KdZ6UHbCefNYHF4qiPjETx/Untitled?57:20)
