### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by phuongth-0535** [phuongth-0535/figma-plugin-demo#43]
```tsx
// components/Homepage.tsx

import React from 'react';
import '~/components/Button';

export const Homepage: React.FC = () => {
  const redirectToHomepage = () => {
    // Function to redirect to homepage
    // Implement the redirect logic here
  };

  const openLoginDialog = () => {
    // Function to open the login dialog
    // Implement the login dialog opening logic here
  };

  const redirectToSignupPage = () => {
    // Function to redirect to /signup page
    // Implement the redirect logic here
  };

  return (
    <div className="homepage">
      <div className="header">
        <span className="company" onClick={redirectToHomepage}>Company</span>
        <Button text="Login" onClick={openLoginDialog} />
      </div>
      <svg
        width="112.801px"
        height="112.801px"
        viewBox="0 0 112.801 112.801"
        className="arrow-1"
        onClick={redirectToHomepage}
      >
        <g transform="rotate(-37.073 56.4005 56.4005)">
          <line x1="0" y1="56.4" x2="112.8" y2="56.4" style={{ stroke: '#000', strokeWidth: '2' }} />
        </g>
      </svg>
      <Button text="Sign up" onClick={redirectToSignupPage} />
    </div>
  );
};
```

```css
/* styles/homepage.css */

.homepage .header {
  width: 317px;
  height: 45px;
  padding: 8px 9px 9px 0px;
  align-items: center;
  gap: 143px;
  flex-shrink: 0;
  background: #8250DF;
}

.homepage .company {
  display: flex;
  width: 82px;
  height: 24px;
  flex-direction: column;
  justify-content: center;
  flex-shrink: 0;
  color: #FFF;
  text-align: center;
  font-family: 'Inter', sans-serif;
  font-size: 12px;
  font-style: normal;
  font-weight: 400;
  line-height: normal;
  cursor: pointer;
}

.homepage .arrow-1 {
  cursor: pointer;
}
```

Please note that I have added a `cursor: pointer;` style to both `.company` and `.arrow-1` CSS classes to indicate that these are clickable. Additionally, the `Button` component is imported from the '~/components' folder but the implementation is not shown here because it's presumed to be an existing component. You should implement the `redirectToHomepage`, `openLoginDialog`, and `redirectToSignupPage` functions according to your routing and dialog logic.

[Open in Figma](https://www.figma.com/file/KdZ6UHbCefNYHF4qiPjETx/Untitled?57:20)
