### ISSUE TITLE
Section 5

### ISSUE THREAD

**Issue by phuongth-0535** [phuongth-0535/figma-plugin-demo#45]
```css
/* styles.css */

.rectangle-2 {
  width: 84px;
  height: 59px;
  background: #D9D9D9;
}
```

```tsx
// Section5.tsx

import React from 'react';
import './styles.css';

const Section5: React.FC = () => {
  return (
    <section>
      <div className="rectangle-2"></div>
    </section>
  );
};

export default Section5;
```

[Open in Figma](https://www.figma.com/file/KdZ6UHbCefNYHF4qiPjETx/Untitled?181:6)
