### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by phuongth-0535** [phuongth-0535/figma-plugin-demo#46]
```tsx
// components/Homepage.tsx

import React from 'react';
import Button from '~/components/Button';

export const Homepage: React.FC = () => {
  const handleArrowClick = () => {
    // Implement your logic to redirect to homepage or open login dialog
  };

  const handleSignUpClick = () => {
    window.location.href = '/signup';
  };

  const handleLoginClick = () => {
    // Implement your logic to open the login dialog
  };

  const handleCompanyClick = () => {
    window.location.href = '/';
  };

  return (
    <section className="homepage">
      <div className="header-container">
        <span className="company" onClick={handleCompanyClick}>Company</span>
        <Button text="Login" onClick={handleLoginClick} />
      </div>
      <svg
        className="arrow"
        width="112.801px"
        height="0px"
        onClick={handleArrowClick}
        style={{ transform: "rotate(-37.073deg)" }}
        strokeWidth="2px"
        stroke="#000"
      />
      <Button text="Sign up" onClick={handleSignUpClick} />
    </section>
  );
};

```

```css
/* styles.css */

.homepage {
  /* Add styles for homepage if needed */
}

.header-container {
  display: flex;
  width: 317px;
  height: 45px;
  padding: 8px 9px 9px 0px;
  align-items: center;
  gap: 143px;
  flex-shrink: 0;
  background-color: #8250DF;
}

.company {
  display: flex;
  width: 82px;
  height: 24px;
  flex-direction: column;
  justify-content: center;
  flex-shrink: 0;
  color: #FFF;
  text-align: center;
  font-family: Inter;
  font-size: 12px;
  font-style: normal;
  font-weight: 400;
  line-height: normal;
  cursor: pointer; /* Assuming company name should be clickable */
}

.arrow {
  /* Arrow specific styles, if needed */
  cursor: pointer; /* Assuming arrow should be clickable */
}

```
Please note that the button component is imported and used with the text prop, which will need to be adjusted according to how the Button component expects props. Additionally, inline styles are used for the SVG as it includes rotations and other properties that are not as straightforward to convert to CSS classes. Also, clicking functionalities are assumed based on the comments and simple logic has been provided; adjust them as needed to fit the full requirements of your application.

[Open in Figma](https://www.figma.com/file/KdZ6UHbCefNYHF4qiPjETx/Untitled?57:20)
