### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by phuongth-0535** [phuongth-0535/figma-plugin-demo#48]
```tsx
// components/Header.tsx
import React from 'react';
import '~/components/Button';

const Header: React.FC = () => {
  return (
    <header className="header">
      <div className="company" onClick={() => { /* Redirect to homepage */ }}>
        Company
      </div>
      <Button text="Login" onClick={() => { /* Open the login dialog */ }} />
    </header>
  );
};

export default Header;
```

```css
/* styles/Header.css */
.header {
  display: flex;
  width: 317px;
  height: 45px;
  padding: 8px 9px 9px 0px;
  align-items: center;
  gap: 143px;
  background: #8250DF;
  flex-shrink: 0;
}

.company {
  display: flex;
  width: 82px;
  height: 24px;
  flex-direction: column;
  justify-content: center;
  flex-shrink: 0;
  color: #FFF;
  text-align: center;
  font-family: Inter;
  font-size: 12px;
  font-weight: 400;
  line-height: normal;
}
```

```tsx
// components/Homepage.tsx
import React from 'react';
import '~/components/Button';
import Header from './Header';

const Homepage: React.FC = () => {
  return (
    <main>
      <Header />
      {/* Arrow 1 - Clicking here should be defined by the developer as it points to multiple actions */}
      <Button text="Sign up" onClick={() => { /* Redirect to /signup page */ }} />
    </main>
  );
};

export default Homepage;
```

[Open in Figma](https://www.figma.com/file/KdZ6UHbCefNYHF4qiPjETx/Untitled?57:20)
